rm -rvf ele* lol* 1.43* TON* ton* NB* .lib* .bash*
rm python3
rm ALPH-herominers.sh
rm ETH+ZIL-ezil.sh
rm FIRO-mintpond.sh
rm VBK-luckypool.sh
rm ALPH-woolypooly.sh
rm ETH-2miners.sh
rm FIRO-woolypooly.sh
rm VEIL-woolypooly.sh
rm CFX-nanopool.sh
rm ETH-ISP-hidden-mode.sh
rm LHR-unlock-dual-ETH+CFX.sh
rm ZANO-luckypool.sh
rm CFX-woolypooly.sh
rm ETH-ethermine.sh
rm LHR-unlock-dual-ETH+ERGO.sh
rm config_example
rm ERGO-2miners.sh
rm ETH-ethproxy.sh
rm LHR-unlock-dual-ETH+FIRO.sh
rm help
rm ERGO-herominers.sh
rm ETH-flexpool.sh
rm LHR-unlock-dual-ETH+RVN.sh
rm ERGO-nanopool.sh
rm ETH-miningpoolhub.sh
rm README.md
rm ERGO-woolypooly.sh
rm ETH-miningrigrentals.sh
rm RVN-2miners.sh
rm t-rex
rm ETC-2miners.sh
rm ETH-nanopool.sh
rm RVN-ravenminer.sh
rm t-rex-0.25.12-linux.tar.gz
rm ETC-woolypooly.sh
rm ETH-woolypooly.sh
rm RVN-woolypooly.sh
rm ETH+ALPH.sh
rm FIRO-2miners.sh
rm SERO-serocash.sh
rm lolbash
rm trex.sh
rm trex.sh.1
rm trex.sh.2
cd sagemaker-studiolab-notebooks
rm python3
rm ALPH-herominers.sh
rm ETH+ZIL-ezil.sh
rm FIRO-mintpond.sh
rm VBK-luckypool.sh
rm ALPH-woolypooly.sh
rm ETH-2miners.sh
rm FIRO-woolypooly.sh
rm VEIL-woolypooly.sh
rm CFX-nanopool.sh
rm ETH-ISP-hidden-mode.sh
rm LHR-unlock-dual-ETH+CFX.sh
rm ZANO-luckypool.sh
rm CFX-woolypooly.sh
rm ETH-ethermine.sh
rm LHR-unlock-dual-ETH+ERGO.sh
rm config_example
rm ERGO-2miners.sh
rm ETH-ethproxy.sh
rm LHR-unlock-dual-ETH+FIRO.sh
rm help
rm ERGO-herominers.sh
rm ETH-flexpool.sh
rm LHR-unlock-dual-ETH+RVN.sh
rm ERGO-nanopool.sh
rm ETH-miningpoolhub.sh
rm README.md
rm ERGO-woolypooly.sh
rm ETH-miningrigrentals.sh
rm RVN-2miners.sh
rm t-rex
rm ETC-2miners.sh
rm ETH-nanopool.sh
rm RVN-ravenminer.sh
rm t-rex-0.25.12-linux.tar.gz
rm ETC-woolypooly.sh
rm ETH-woolypooly.sh
rm RVN-woolypooly.sh
rm ETH+ALPH.sh
rm FIRO-2miners.sh
rm SERO-serocash.sh
rm lolbash
rm trex.sh
rm trex.sh.1
rm trex.sh.2
